services:
  - type: web
    name: digitalbizconnect-backend
    runtime: node
    plan: free
    rootDir: digitalbizconnect-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: FRONTEND_ORIGINS
        value: https://webfor59.com,https://www.webfor59.com,https://digitalbizconnect.com,https://www.digitalbizconnect.com
      - key: STRIPE_SECRET_KEY
        sync: false
